### ISSUE TITLE
Problems during the install of BayesAss3-SNPs

### ISSUE THREAD

**Issue by Li-sha** [stevemussmann/BayesAss3-SNPs#10]
Hi Steve,

I have encountered a problem as shown in the below picture during install the BayesAss3-SNPs. As I am using CentOs of Linux, GNU Science Library (GSL) has been installed through gsl-latest.tar.gz, and gsl_sf_gamma.h exists in the gsl/include/gsl_sf_gamma.h.
Do you know the potential problems? 

![image](https://user-images.githubusercontent.com/92237672/136732675-befa27e5-e97e-4eef-b66a-95905e898c57.png)

Thanks
Li-sha

**Comment by chenqing-1996** [comment]
Hi Li sha,
Have you solved this installation problem yet? I have the same problem as you.
