### ISSUE TITLE
BA3_SNPs_autotune being or not?

### ISSUE THREAD

**Issue by HanXiaoEvo** [stevemussmann/BayesAss3-SNPs#6]
Hi Steve,

I am trying BayesAss-SNPs right now and it works fine as I feel (just started and showing only % done).

I am wondering if there is BA3_SNPs_autotune inside of BayesAss-SNPs as you mentioned in the MEE paper. If not, how should I know about the performance of the parameters, or I should also set it by myself? Thank you very much!

Best regards,
Han Xiao

**Comment by stevemussmann** [comment]
Hello,

The autotune package is separate from BA3-SNPs. It is located here: https://github.com/stevemussmann/BA3-SNPS-autotune, The README file contains information for installing and running this package.

For learning more about the mixing parameters, I suggest reading the user manual for the original BayesAss. A link to this manual is provided in the README on this repository (BayesAss3-SNPs). 

I hope that helps,

-Steve
