### ISSUE TITLE
Filter loci in input file

### ISSUE THREAD

**Issue by deleod** [stevemussmann/BayesAss3-SNPs#8]
Hi, do you have any suggestions (or scripts) on how to remove loci where data is missing for all individuals. I am having an issue running the program with my input file and believe this is the culprit. 
`>BA3-SNPS -v -i100000000 -b1000000 -t -g -u -l 21292 -F wgenome_20_BA3.txt

                   BA3-SNPS Version 1.1 (BA3-SNPS)                  
                        Released: 07/11/2019                        
                          Steven Mussmann                           
         Department of Biological Sciences at U. of Arkansas        

                 Modified from BayesAss Version 3.0.4               
                            Bruce Rannala                           
           Department of Evolution and Ecology at UC Davis          

Please cite: Wilson & Rannala (2003). Bayesian Inference of recent  
migration rates using multilocus genotypes. Genetics 163:1177-1191. 

Please also cite: Mussmann, Douglas, Chafin, & Douglas (2019). BA3- 
SNPs: Contemporary migration reconfigured in BayesAss for next-     
generation sequence data. Methods in Ecology and Evolution.         

Made new Indiv object
Going to read input file
Setting alleles
pop_1	0
Read input file

At least one locus may contain no data for all samples in your input file.
gsl: ../gsl/gsl_rng.h:200: ERROR: invalid n, either 0 or exceeds maximum value of generator
Default GSL error handler invoked.
Abort trap: 6
`

**Comment by stevemussmann** [comment]
If you have a copy of your SNP data file in a VCF format, that can easily be accomplished with VCFtools or BCFtools. I'm not aware of anything that filters the immanc format used by BayesAss.

**Comment by deleod** [comment]
Ok, thanks. I do have a vcf file so I will look into VCFtools to filter and try re-running.

**Comment by stevemussmann** [comment]
Yeah, sorry, I'm not aware of anything that filters Structure files directly.

**Comment by deleod** [comment]
Apprecaite the tip! Will attempt to do this with the vcf file if needed.
Not sure how straightforward it is to convert vcf to immanc though for
Bayesass?

May have found a work around for filtering the structure file directly in R
using the poppr package, missingno function. Will report back.

**Comment by stevemussmann** [comment]
Usually I end up going through an intermediate format or two. There's a vcf2phylip converter (https://github.com/edgardomortiz/vcf2phylip), then I convert to structure (https://github.com/stevemussmann/file_converters/blob/master/phy2str.pl) and finally use the pyradStr2immanc.pl converter. It's far from the most efficient thing, but I'm not aware of any converters that would go direct from VCF to immanc. Maybe PGDSpider, but I've had mixed experiences with that program.

**Comment by stevemussmann** [comment]
In my experience segmentation faults usually result from specifying an incorrect number of loci. If you converted to immanc with my perl script, you should be able to check the number of loci using `awk '{print $3}' filename.txt | sort | uniq | wc -l` and replacing "filename.txt" with the name of your file.

**Comment by deleod** [comment]
Ahh, not sure how I missed this. Thank you!
